### ISSUE TITLE
Why is everything interface{}?

### ISSUE THREAD

**Issue by cathalgarvey** [kurrik/twittergo#11]
I'm looking through models.go and it looks like most of the logic is performed upon subtypes of `map[string]interface{}` or `[]interface{}`, with type-casting to expected types within the function and method code; why not use structs?

Not be snarky, just trying to understand the implementation.

**Comment by kurrik** [comment]
It's a good question.  Twitter changes their API from time to time.  For example, the favorite count field used to be a number if the count was under 50 (iirc) and then "50+" as a string when the count exceeded that amount.  Now it's always a number so this point isn't valid.  It was a poorly designed API in that regard.

So this was to be more resilient to deserialization problems, new fields appearing, expected fields disappearing, etc.  I'm not sure I would do it exactly the same way now given that Twitter's API has become way more stable (this is unfortunately seemingly from a lack of updates to be honest).

You should still be able to use the core library with struct models, but you'd need to manage your own deserialization then.  

Happy to answer more questions if you have them, this was a very early Go project for me so I've tried to keep it up to date but there are probably at least a few more "huh" decisions in there.

**Comment by cathalgarvey** [comment]
Thanks for the insight! Can see where you're coming from re:Twitter's flakiness. :)

**Comment by kurrik** [comment]
One more note - I had been debating merging https://github.com/kurrik/twittergo/pull/10 which changes the json deserializer back into `encoding/json` (I wound up using a different deserializer for a while for various reasons). 

I just merged that, so now (once you `go get -u github.com/kurrik/twittergo`) you can pass a struct with annotated fields to `resp.Parse` (like you would when deserializing a JSON blob normally) so it should be easier to use your own models.

**Comment by kurrik** [comment]
And here's an example of using a custom struct: https://github.com/kurrik/twittergo-examples/blob/master/custom_struct/main.go
