### ISSUE TITLE
ability to deserialize different tweet values

### ISSUE THREAD

**Issue by entro-pi** [kurrik/twittergo#18]
Would you be interested in a pull request that adds another field or type to the Tweet or Timeline objects? I love your project, very intuitive. I just found I had a use for  other values, and made a few changes to allow for grabbing the status in  reply to, and will probably make a few more to do the things I want to  eventually.
--py-entro

**Comment by kurrik** [comment]
Absolutely!

**Comment by localtoastdotnet** [comment]
Cool! I'll be back.
