### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by shreyall** [kurrik/twittergo#20]
hi, I'm trying to obtain lists owned by a user, but end up getting a 400 bad request - not sure how to debug, any help ?

**Comment by shreyall** [comment]
> hi, I'm trying to obtain lists owned by a user, but end up getting a 400 bad request - not sure how to debug, any help ?

`func main() {
	//getFollowers()

	var (
		err    error
		client *twittergo.Client
	)

	const path, screen_name = "/1.1/lists/list.json", "mejja"
	const user_id = "1412977753595551744"

	if client, err = loadCredentials(); err != nil {
		fmt.Printf("Could not load CREDENTIALS fil: %v\n", err)
		os.Exit(1)
	}

	query := url.Values{}
	query.Set("user_id", user_id)

	err = fetchList(client, path, query)

	fmt.Println("===================================== mainc")
	fmt.Printf("in main, err %v\n", err)

}

func fetchList(client *twittergo.Client, path string, query url.Values) (err error) {
	u := fmt.Sprintf("%v?%v", path, query.Encode())

	req, err := http.NewRequest("GET", u, nil)
	if err != nil {
		return fmt.Errorf("Could not parse request: %v\n", err)
	}

	resp, err := client.SendRequest(req)
	if err != nil {
		err = fmt.Errorf("could not send request: %v\n", err)
		return
	}

	fmt.Println("===================================== req")
	fmt.Println(req)
	fmt.Println()
	fmt.Println("===================================== resp")
	fmt.Println(resp.HasRateLimit())
	fmt.Println(resp)

	return
}`

**Comment by kurrik** [comment]
Hi, sorry for the delayed response here.  I set up the example you ran and got a valid API response with the following:

```
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/kurrik/oauth1a"
	"github.com/kurrik/twittergo"
)

func loadCredentials() (client *twittergo.Client, err error) {
	credentials, err := ioutil.ReadFile("CREDENTIALS")
	if err != nil {
		return
	}
	lines := strings.Split(string(credentials), "\n")
	config := &oauth1a.ClientConfig{
		ConsumerKey:    lines[0],
		ConsumerSecret: lines[1],
	}
	user := oauth1a.NewAuthorizedConfig(lines[2], lines[3])
	client = twittergo.NewClient(config, user)
	return
}

func main() {
	//getFollowers()

	var (
		err    error
		client *twittergo.Client
	)

	const path, screen_name = "/1.1/lists/list.json", "mejja"
	const user_id = "1412977753595551744"

	if client, err = loadCredentials(); err != nil {
		fmt.Printf("Could not load CREDENTIALS fil: %v\n", err)
		os.Exit(1)
	}

	query := url.Values{}
	query.Set("user_id", user_id)

	err = fetchList(client, path, query)

	fmt.Println("===================================== mainc")
	fmt.Printf("in main, err %v\n", err)

}
func fetchList(client *twittergo.Client, path string, query url.Values) (err error) {
	u := fmt.Sprintf("%v?%v", path, query.Encode())

	req, err := http.NewRequest("GET", u, nil)
	if err != nil {
		return fmt.Errorf("Could not parse request: %v\n", err)
	}

	resp, err := client.SendRequest(req)
	if err != nil {
		err = fmt.Errorf("could not send request: %v\n", err)
		return
	}

	fmt.Printf("Resp body: %v\n", resp.ReadBody())

	fmt.Println("===================================== req")
	fmt.Println(req)
	fmt.Println()
	fmt.Println("===================================== resp")
	fmt.Println(resp.HasRateLimit())
	fmt.Println(resp)

	return
}
```

Note the `fmt.Printf("Resp body: %v\n", resp.ReadBody())` which I added to look at the response body.  On a valid request you'll see the JSON:
```
Resp body: [{"id":1348100623749804034,"id_str":"1348100623749804034","name": ...
```
If the CREDENTIALS file is somehow invalid, the response is:
```
Resp body: {"errors":[{"code":215,"message":"Bad Authentication data."}]}
```
