### ISSUE TITLE
twittergp despm returns empty 403 bodies sometimes

### ISSUE THREAD

**Issue by jmhodges** [kurrik/twittergo#8]
Which causes very confusing errors in resp.Parse(). Specifcally, it'll return fmt.Errorf(`""`) because of [line 199 in models.go](https://github.com/kurrik/twittergo/blob/master/models.go#L199).

I haven't figured out why it's returning 403 with empty bodies (my anaconda set up worked perfectly, so this is confusing).

Two things seem to have to happen: that error message has to be improved, and the case of empty bodies on 403s has to be handled.

The error message can be marginally improved by changing that out to 
     
    err = fmt.Errorf("unable to unmarshal Twitter error object (status code %d): %v", r.StatusCode, string(b))

but it would probably be best if that was a specific type so developers can handle it better.

**Comment by kurrik** [comment]
Hi Jeff, thanks for reporting the issue.  Makes a lot of sense, so I've updated the error responses from the Parse call.

**Comment by jmhodges** [comment]
Thanks! Sorry for the duplicate! My chrome got a little wacky when making them.

**Comment by kurrik** [comment]
No worries at all.  Let me know if you have any other suggestions as you use the library - it's been a while since I've needed it for anything but I do want to keep maintaining it
